### ISSUE TITLE
[Linux] Overlay Layers Do not Appear To Work

### ISSUE THREAD

**Issue by d10sfan** [Try/Tempest#13]
This was mainly tested with the Steam Overlay. Normally if you add a game as a non-steam game, it'll try and load up the overlay as well. In this case, it never appears.

I attempted to add an activation of the layer, which the logs seem to show that the layer was being enabled. A link to a patch showing what was changed: [0001-Attempt-at-getting-steam-overlay-enabled.zip](https://github.com/Try/MoltenTempest/files/4537083/0001-Attempt-at-getting-steam-overlay-enabled.zip)

I'm wondering if it might have something to do with the hidden window being created and then destroyed, as in possibly the overlay layer library is seeing that thinking it needs to inject into it and getting confused.

Was curious if you had any pointers or had ideas as to a fix.

**Comment by Try** [comment]
Hi, @d10sfan !

I've checked your patch and attempt doesn't look correct to me. Vulkan overlays should work without any changes from app.
It possible, that it is some kind of steam issue, possibly overlay is hard disabled for gothic2. 
Another thing I want to mention: RenderDoc overlay works for me.

Can you, plase, verify that it is not a steam problem, by running follow script:
```bash
export VK_INSTANCE_LAYERS=VK_LAYER_VALVE_steam_overlay_64
./Gothic2Notr -g /path/to/game
```
?

**Comment by d10sfan** [comment]
Ah ok, thanks for looking into it. 

It does look like steam has the SteamOverlay disabled for it (from looking at the steamdb entry for it). It's strange that it'd affect a "non-steam" game for it, but maybe it's looking for an executable name or app label to determine it.

I suppose this can be closed then since it's probably a steam problem.

**Comment by d10sfan** [comment]
When I run that script above, the steam overlay does not appear. It just works as normal
